site:
  title: My API Document
  start_page: docs::index.adoc

content:
  sources:
    - url: https://github.com/adarsh-bm12/antora-docs.git
      branches: main   # Adjust branch name if needed
      start_path: docs  # Change if your AsciiDoc files are in a different folderAdjust this based on your folder structure


asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: '@'


ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

runtime:
  fetch: true


output:
  dir: /var/www/html


